; PlatformIO Project Configuration File
; 
; Not required if you stick to the Arduino IDE
; 
; Build the PlatformIO version directly from the repo without copying files into
; a separate project tree.

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_src_filter = +<usingPlatformIO/main.cpp> ; points to relevant file (ignore existing .ino)
lib_deps = fastled/FastLED@^3.10.3
